apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  mode: Pipeline
  pipeline:
  - step: patch-storage-bucket
    functionRef:
      name: function-cue
    input:
      apiVersion: cue.fn.crossplane.io/v1beta1
      kind: CUEInput
      metadata:
        name: patch-xr
      export:
        target: PatchResources
        resources:
        - name: bucket
          base:
            apiVersion: nobu.dev/v1
            kind: Bucket
            metadata:
              name: test-bucket
        value: |
          // Target the bucket by name
          name: "bucket"
          base: {
            // Add fields here
            metadata: annotations: {
                "nobu.dev/cueified": "true",
                "nobu.dev/app": "someapp",
            }
            
            spec: forProvider: policy: "some-bucket-policy"
          }
