apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  mode: Pipeline
  pipeline:
  - step: conditional
    functionRef:
      name: function-cue
    input:
      apiVersion: cue.fn.crossplane.io/v1beta1
      kind: CUEInput
      metadata:
        name: multiple-objects
      export:
        target: Resources
        options:
          expressions:
          - yaml.MarshalStream(output)
        value: |
          output: [
          	{
                name: "example-cluster"
                base: {
          	  	  apiVersion: "nobu.dev/v1"
            	  kind:       "Cluster"
                }
          	},
          	{
                name: "example-network"
                base: {
          		  apiVersion: "nobu.dev/v1"
          	  	  kind:       "Network"
                }
          	},
          	{
                name: "example-memorystore"
                base: {
          		  apiVersion: "nobu.dev/v1"
          		  kind:       "Memorystore"
                }
          	},
          	{
                name: "example-firewalls"
                base: {
          	  	  apiVersion: "nobu.dev/v1"
            	  kind:       "Firewalls"
                }
          	},
          	{
                name: "example-nodepools"
                base: {
          		  apiVersion: "nobu.dev/v1"
          		  kind:       "Nodepool"
                }
          	},
          ]
