apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  mode: Pipeline
  pipeline:
  - step: conditional
    functionRef:
      name: function-cue
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: CUEInput
      metadata:
        name: injections
      export:
        target: Resources
        options:
          inject:
          - name: provider
            path: spec.provider
        value: |
          #env: string @tag("provider")
          
          if #env == "aws" {
          	apiVersion: "eks.nobu.dev/v1beta"
          }
          if #env == "gcp" {
          	apiVersion: "gke.nobu.dev/v1beta1"
          }
          
          kind: "XNodepool"
          metadata: name: "TestNodepool"
          spec: parameters: {
          	autoscaling: [{
          		maxNodeCount: 1
          		minNodeCount: 1
          	}]
          	clusterName: "example-injections"
          	region: "us-east-2"
          }