name: Build Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Setup Go 1.21
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
    - name: Build
      run: go build .
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Setup Go 1.21
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
    - name: Test
      run: go test -v ./...
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
